In [13]:
import numpy as np
np.random.seed(0)
def reciprocal_values(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        
        output[i] = 1.0/values[i]
    return output
values = np.random.randint(1,10, size = 5)
print(values)
reciprocal_values(values)

[6 1 4 4 8]


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [9]:
values = np.random.randint(1,100, size = 1000000)
%timeit reciprocal_values(values)

2.83 s ± 236 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
np.random.seed(0)
values = np.random.randint(1,10, size =5)
print(reciprocal_values(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [21]:
values = np.random.randint(1,100,size = 1000000)
print(1.0/values)
%timeit 1.0/values

[0.01204819 0.03448276 0.01219512 ... 0.04       0.02272727 0.02777778]
5.03 ms ± 648 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [23]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [24]:
print(y/x)

[0.         0.5        0.66666667 0.75       0.8       ]


And ufunc operations are not limited to one-dimensional arrays–they can also act on multi-dimensional arrays as well:

In [27]:
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
mat**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

Computations using vectorization through ufuncs are nearly always more efficient than their counterpart implemented using Python loops, especially as the arrays grow in size. Any time you see such a loop in a Python script, you should consider whether it can be replaced with a vectorized expression.

### Array Arithmatic

NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators. The standard addition, subtraction, multiplication, and division can all be used:

In [32]:
x = np.arange(1,6)
print("x = ", x)
print("x+5 = ", x+5)
print("x-5 = ", x-5)
print("x*2 = ", x*2)
print("x/2 = ", x/2)
print("x//2 = ", x//2)# floor division
print("-x  =", -x)
print("x**2 =", x**2)
print("x%2 =", x%2 )

x =  [1 2 3 4 5]
x+5 =  [ 6  7  8  9 10]
x-5 =  [-4 -3 -2 -1  0]
x*2 =  [ 2  4  6  8 10]
x/2 =  [0.5 1.  1.5 2.  2.5]
x//2 =  [0 1 1 2 2]
-x  = [-1 -2 -3 -4 -5]
x**2 = [ 1  4  9 16 25]
x%2 = [1 0 1 0 1]


To print prime numbers between limits

In [77]:
lower = 2
upper = 20
for num in range(lower, upper+1):
    if num>1:
        for i in range(2,num):
            if (num%i == 0):
               break
        else:
            print(num, "is a prime number")

2 is a prime number
3 is a prime number
5 is a prime number
7 is a prime number
11 is a prime number
13 is a prime number
17 is a prime number
19 is a prime number


To print Prime and Non-Prime numbers between limts

In [75]:
lower = 2
upper = 10

print("Prime numbers between", lower, "and", upper, "are:")

for num in range(lower, upper):
   # all prime numbers are greater than 1
   if num > 1:
       for i in range(2, int(num/2)+1):
           if (num % i) == 0:
                print(num,"is not a prime number" )
                break
       else:
           print(num, "is a prime number")

Prime numbers between 2 and 10 are:
2 is a prime number
3 is a prime number
4 is not a prime number
5 is a prime number
6 is not a prime number
7 is a prime number
8 is not a prime number
9 is not a prime number


To find whether the given number is prime or not

In [74]:
# Python program to check if
# given number is prime or not
num = 17
# If given number is greater than 1
if num > 1:
  # Iterate from 2 to n / 2
    for i in range(2, int(num/2)+1):
        # If num is divisible by any number between
        # 2 and n / 2, it is not prime
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")

17 is a prime number


In [73]:
lower = 2
upper = 9
for num in range(lower, upper+1):
    if num>1:
        for i in range(2, int(num/2)+1):
            if(num%2 ==0):
                print(num,"is not a prime number")
                break
        else:
                print(num,"is a prime number")


2 is a prime number
3 is a prime number
4 is not a prime number
5 is a prime number
6 is not a prime number
7 is a prime number
8 is not a prime number
9 is a prime number


In [80]:
x = np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [82]:
-(0.5*x+1)**2

array([ -2.25,  -4.  ,  -6.25,  -9.  , -12.25, -16.  , -20.25, -25.  ,
       -30.25])

In [83]:
np.add(x,2)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
x = np.array([-2,-4,1,2,3])
abs(x)

array([2, 4, 1, 2, 3])

In [86]:
y = np.subtract(x,2)
print(y)

[-4 -6 -1  0  1]


In [87]:
y = np.power(x,2)
print(y)

[ 4 16  1  4  9]


In [89]:
np.abs(x)

array([2, 4, 1, 2, 3])

In [90]:
np.absolute(x)

array([2, 4, 1, 2, 3])

This ufunc can also handle complex data, in which the absolute value returns the magnitude:

In [93]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [94]:
y = np.array([2-3j, 3-2j])
np.absolute(y)

array([3.60555128, 3.60555128])

### Trigonometric functions

In [97]:
Theta = np.linspace(0, np.pi, 3)
print("Theta:", Theta)
print("Cos(Theta):", np.cos(Theta))
print("sin(Theta):", np.sin(Theta))

Theta: [0.         1.57079633 3.14159265]
Cos(Theta): [ 1.000000e+00  6.123234e-17 -1.000000e+00]
sin(Theta): [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [98]:
x = [-1, 0, 1]
print("arcsin:", np.arcsin(x))

arcsin: [-1.57079633  0.          1.57079633]


In [99]:
print("arccos:", np.arccos(x))

arccos: [3.14159265 1.57079633 0.        ]


In [102]:
print("arctan:", np.arctan(x))

arctan: [-0.78539816  0.          0.78539816]


### Exponents and logarithms

Another common type of operation available in a NumPy ufunc are the exponentials:

In [115]:
X = [1,2,3]
print("x:", x)
print("e^x:", np.exp(x))
print("2^x:", np.exp2(x))
print("3^x:", np.power(x, 3))

x: [1, 2, 4, 10]
e^x: [2.71828183e+00 7.38905610e+00 5.45981500e+01 2.20264658e+04]
2^x: [   2.    4.   16. 1024.]
3^x: [   1    8   64 1000]


The inverse of the exponentials, the logarithms, are also available. The basic np.log gives the natural logarithm; if you prefer to compute the base-2 logarithm or the base-10 logarithm, these are available as well:

In [112]:
x = [1,2,4,10]
print("ln:", np.log(x))

ln: [0.         0.69314718 1.38629436 2.30258509]


In [114]:
print("Log2:", np.log2(x))

Log2: [0.         1.         2.         3.32192809]


In [116]:
print("log10:", np.log10(x))

log10: [0.         0.30103    0.60205999 1.        ]


There are also some specialized versions that are useful for maintaining precision with very small input:

In [120]:
x = [0,0.001,0.01]
print("exp(x)-1:",np.expm1(x))

exp(x)-1: [0.         0.0010005  0.01005017]


In [122]:
print("log(x+1):", np.log1p(x))

log(x+1): [0.         0.0009995  0.00995033]


### Specialized ufuncs

In [123]:
from scipy import special

In [124]:
# Gamma functions (generalized factorials) and related function

x = [1,2,5]
print("gamma:", special.gamma(x))

gamma: [ 1.  1. 24.]


In [125]:
print("gammaln:", special.gammaln(x))

gammaln: [0.         0.         3.17805383]


In [126]:
print("beta:", special.beta(x,2))

beta: [0.5        0.16666667 0.03333333]


In [128]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0,0.3,0.7,0.9])
print("err:", special.erf(x))

err: [0.         0.32862676 0.67780119 0.79690821]


In [129]:
print("errfc:",special.erfc(x))

errfc: [1.         0.67137324 0.32219881 0.20309179]


In [130]:
print("erfinv:", special.erfinv(x))

erfinv: [0.         0.27246271 0.73286908 1.16308715]


In [134]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,3, out = y)
print(y)

[ 0.  3.  6.  9. 12.]


In [135]:
y = np.zeros(10)
np.power(x,2,out = y[::2])
print(y)

[ 0.  0.  1.  0.  4.  0.  9.  0. 16.  0.]


### Agregates

For binary ufuncs, there are some interesting aggregates that can be computed directly from the object. For example, if we'd like to reduce an array with a particular operation, we can use the reduce method of any ufunc. A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

For example, calling reduce on the add ufunc returns the sum of all elements in the array:

In [137]:
x = np.arange(1,5)
np.add.reduce(x)

10

Similarly, calling reduce on the multiply ufunc results in the product of all array elements:

In [138]:
np.multiply.reduce(x)

24

If we'd like to store all the intermediate results of the computation, we can instead use accumulate:

In [139]:
np.add.accumulate(x)

array([ 1,  3,  6, 10], dtype=int32)

In [140]:
np.multiply.accumulate(x)

array([ 1,  2,  6, 24], dtype=int32)

### Outer products

Finally, any ufunc can compute the output of all pairs of two different inputs using the outer method. This allows you, in one line, to do things like create a multiplication table:

In [141]:
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])